Let's import the NumPy library

In [140]:
import numpy as np

In [141]:
my_array = np.array([1, 2, 3, 4, 5])
my_array

array([1, 2, 3, 4, 5])

In [142]:
my_array[0]  # Accessing the first element of the array 


np.int64(1)

In [143]:
my_array[4]

np.int64(5)

In [144]:
my_array[3:]

array([4, 5])

In [145]:
my_array[1:5] # Accessing elements from index 1 to index 4 (5 is exclusive)

array([2, 3, 4, 5])

In [146]:
my_array[4:] # Accessing elements from index 4 to the end of the array

array([5])

In [147]:
my_array[:4] # Accessing elements from the start of the array to index 3 (4 is exclusive)

array([1, 2, 3, 4])

In [148]:
my_array[::2]

array([1, 3, 5])

In [149]:
my_array[::-1] # Accessing elements in reverse order

array([5, 4, 3, 2, 1])

In [150]:
ages_list = [18, 15, 23, 14, 20]

In [151]:
# ages_list >= 18  # cannot compare lists to integers
ages = np.array(ages_list)

In [152]:
ages >= 18  # This will return a boolean array indicating which ages are greater than or equal to 18    

array([ True, False,  True, False,  True])

In [153]:
ages[ages >= 18]  # This will return a new array containing only the ages that

array([18, 23, 20])

In [154]:
ages[[True, False, True, False, True]]

array([18, 23, 20])

In [155]:
#Fancy indexing with NumPy allows you to access elements of an array using another array of indices or boolean values. This can be useful for selecting specific elements based on certain conditions or criteria.
my_array[[4, 0, 1]]

#Fancy indexing with NumPy allows you to access elements of an array using another array of indices or boolean values. now this is a fancy indexing [4, 0, 1] which means we are accessing the elements at index 4, 0, and 1 of my_array. The result will be a new array containing the values at those indices.

array([5, 1, 2])

In [156]:
my_array[[4, 0, 0, 0]] #Fancy indexing with repeated indices. This will return a new array containing the elements at index 4, 0, 0, and 0 of my_array. The result will be [5, 1, 1, 1] since the element at index 0 is repeated three times.

array([5, 1, 1, 1])

In [157]:
indices = np.where(my_array % 2 == 0)
indices

(array([1, 3]),)

In [158]:
my_array[indices]

array([2, 4])

In [159]:
np.where(ages % 2 == 0)

(array([0, 3, 4]),)

In [160]:
my_array

array([1, 2, 3, 4, 5])

In [161]:
np.where(my_array > 2, 100, my_array)  # (condition, case if met, else); does not act in place
# this will return a new array where all elements greater than 2 are replaced with 100, and all other elements remain unchanged. The result will be [1, 2, 100, 100, 100] since the elements at index 2, 3, and 4 are greater than 2.

array([  1,   2, 100, 100, 100])

In [162]:
new_array = np.where(my_array < 4, my_array ** 2, -65)  # this will return a new array where all elements less than 4 are squared, and all other elements are replaced with -65. The result will be [1, 4, 9, 16, 25] since the elements at index 0, 1, 2, and 3 are less than 4.
new_array

array([  1,   4,   9, -65, -65])

In [163]:
my_array_2 = my_array  # making a deep copy of my_array
my_array_2

array([1, 2, 3, 4, 5])

In [164]:
my_array_2[my_array_2 > 2] = 100
my_array_2

array([  1,   2, 100, 100, 100])

In [165]:
my_array = np.array([1, 2, 3, 4, 5])  # restoring my_array to its initial values

In [166]:
my_array_3 = my_array.copy()  # make a shallow copy
my_array_3

array([1, 2, 3, 4, 5])

In [167]:
my_array_3[my_array_3 > 4] = 100
my_array_3

array([  1,   2,   3,   4, 100])

In [168]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [169]:
matrix[1][2]

np.int64(6)

In [170]:
matrix[1, 2]

np.int64(6)

In [171]:
matrix[:2, 1:] # here we are slicing the matrix to get all rows (up to index 3, exclusive) and columns starting from index 1 to the end. The result will be a new array containing the elements [[2, 3], [5, 6], [8, 9]].   

array([[2, 3],
       [5, 6]])

In [172]:
matrix[2, 1:]

array([8, 9])

In [173]:
matrix[matrix > 2]  # collapses the dimension

array([3, 4, 5, 6, 7, 8, 9])

In [174]:
three_tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]], [[13, 14, 15], [16, 17, 18]]])
three_tensor

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [175]:
three_tensor[1][1][2]

np.int64(12)

In [176]:
three_tensor[three_tensor < 12] #here we are using boolean indexing to select all elements of the three_tensor that are less than 12. The result will be a new array containing the elements [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11] since these are the elements in the three_tensor that satisfy the condition of being less than 12.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [177]:
arr_3D = np.array([
    [[0, 1, 2], [3, 4, 5], [6, 7, 8]],
    [[9, 10, 11], [12, 13, 14], [15, 16, 17]],
    [[18, 19, 20], [21, 22, 23], [24, 25, 26]]
])
arr_3D[1][1] #here we are accessing the element at the second row and second column of the second 2D array

array([12, 13, 14])

In [178]:
arr_3D[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [179]:
arr_3D[0, 1, 2] # accessing the element at the first 2D array, second row, third column

np.int64(5)

In [185]:
arr_3D 

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [182]:
arr_3D[:2, :2, :2]    # accessing the first two 2D arrays, first two rows, and first two columns of the first two 2D arrays. The result will be a new array containing the elements [[[0, 1], [3, 4]], [[9, 10], [12, 13]]].

array([[[ 0,  1],
        [ 3,  4]],

       [[ 9, 10],
        [12, 13]]])

The Slicing: arr_3D[:2, :2, :2]
This is a 3D slice with three parameters:

First dimension (depth): :2 → take indices 0 and 1

Second dimension (rows): :2 → take indices 0 and 1

Third dimension (columns): :2 → take indices 0 and 1


Step 1: First dimension [:2]

Selected:
[
  [  // Matrix 0
    [0, 1, 2], [3, 4, 5], [6, 7, 8]
  ],
  [  // Matrix 1
    [9, 10, 11], [12, 13, 14], [15, 16, 17]
  ]
]

Step 2: Second dimension [:2] (within each selected matrix)
text
Matrix 0 → rows 0 and 1:
[
  [0, 1, 2],  // Row 0
  [3, 4, 5]   // Row 1
]

Matrix 1 → rows 0 and 1:
[
  [9, 10, 11],  // Row 0
  [12, 13, 14]  // Row 1
]

Step 3: Third dimension [:2] (within each selected row)
Matrix 0:
Row 0: [0, 1, 2] → [0, 1]  (take columns 0 and 1)
Row 1: [3, 4, 5] → [3, 4]  (take columns 0 and 1)

Matrix 1:
Row 0: [9, 10, 11] → [9, 10]  (take columns 0 and 1)
Row 1: [12, 13, 14] → [12, 13]  (take columns 0 and 1)


Visual Summary
Think of it like this:

First :2 → Keep first 2 "sheets" (depth)

Second :2 → Keep first 2 rows in each sheet

Third :2 → Keep first 2 columns in each row

In [186]:
arr_3D

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [183]:
arr_3D[1:, 1:, 1:]  # accessing all 2D arrays starting from the second one, all rows starting from the second one, and all columns starting from the second one. The result will be a new array containing the elements [[[13, 14], [16, 17]], [[22, 23], [25, 26]]].


array([[[13, 14],
        [16, 17]],

       [[22, 23],
        [25, 26]]])

In [187]:
arr_3D[[0, 1, 2], [0, 1, 2], [0, 1, 2]]

array([ 0, 13, 26])

The Expression: arr_3D[[0, 1, 2], [0, 1, 2], [0, 1, 2]]
This has three index arrays, one for each dimension:

Dimension 0 (depth): [0, 1, 2]

Dimension 1 (rows): [0, 1, 2]

Dimension 2 (columns): [0, 1, 2]

How NumPy Processes This
1. NumPy takes these three index arrays and pairs them element-wise
Index arrays:
dim0: [0, 1, 2]
dim1: [0, 1, 2]
dim2: [0, 1, 2]

Pair them together:
(0, 0, 0), (1, 1, 1), (2, 2, 2)

Step 2: Extracting Elements
Coordinate 1: (0, 0, 0)
Go to depth 0, row 0, column 0

Value: 0
arr_3D[0][0][0] = 0

Coordinate 2: (1, 1, 1)
Go to depth 1, row 1, column 1

Value: 13

text
arr_3D[1][1][1] = 13
Coordinate 3: (2, 2, 2)
Go to depth 2, row 2, column 2

Value: 26

text
arr_3D[2][2][2] = 26


Step 3: Result Shape
The result's shape is determined by the shape of the index arrays (all are 1D arrays of length 3):

python
array([0, 13, 26])

Visual Representation
arr_3D = [
  // Depth 0
  [
    [0, 1, 2],     ← (0,0,0) = 0 ✓
    [3, 4, 5],
    [6, 7, 8]
  ],
  // Depth 1
  [
    [9, 10, 11],
    [12, 13, 14],  ← (1,1,1) = 13 ✓
    [15, 16, 17]
  ],
  // Depth 2
  [
    [18, 19, 20],
    [21, 22, 23],
    [24, 25, 26]   ← (2,2,2) = 26 ✓
  ]
]

In [188]:
arr_3D > 15

array([[[False, False, False],
        [False, False, False],
        [False, False, False]],

       [[False, False, False],
        [False, False, False],
        [False,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True],
        [ True,  True,  True]]])

In [189]:
arr_3D[arr_3D > 15]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [190]:
np.where(arr_3D > 15, arr_3D, np.nan)  # retrieve the array element if condition is met, else retrieve np.nan

array([[[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]],

       [[nan, nan, nan],
        [nan, nan, nan],
        [nan, 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]]])

In [193]:
np.where(arr_3D > 15)
# here we are using the np.where() function to find the indices of all elements in arr_3D that are greater than 15. The result will be a tuple of arrays, where each array contains the indices of the elements that satisfy the condition. The first array contains the indices of the 2D arrays, the second array contains the indices of the rows, and the third array contains the indices of the columns. The result will be (array([1, 1, 2, 2]), array([1, 2, 0, 1]), array([2, 2, 0, 1])) since these are the indices of the elements in arr_3D that are greater than 15.   

(array([1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]),
 array([2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2]),
 array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))

Step-by-Step Execution
Step 1: Create the Boolean Mask
arr_3D > 15

Depth 0:
[[False, False, False],    # 0,1,2  → none > 15
 [False, False, False],    # 3,4,5  → none > 15
 [False, False, False]]    # 6,7,8  → none > 15

Depth 1:
[[False, False, False],    # 9,10,11 → none > 15
 [False, False, False],    # 12,13,14 → none > 15
 [False, True,  True]]     # 15,16,17 → 16,17 > 15 ✓

Depth 2:
[[True,  True,  True],     # 18,19,20 → all > 15 ✓
 [True,  True,  True],     # 21,22,23 → all > 15 ✓
 [True,  True,  True]]     # 24,25,26 → all > 15 ✓


Step 2: Find True Positions
(array([1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2]),  # Depth indices
 array([2, 2, 0, 0, 0, 1, 1, 1, 2, 2, 2]),  # Row indices
 array([1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]))  # Column indices

Let's Pair Them Up
(1, 2, 1) → arr_3D[1][2][1] = 16 ✓
(1, 2, 2) → arr_3D[1][2][2] = 17 ✓
(2, 0, 0) → arr_3D[2][0][0] = 18 ✓
(2, 0, 1) → arr_3D[2][0][1] = 19 ✓
(2, 0, 2) → arr_3D[2][0][2] = 20 ✓
(2, 1, 0) → arr_3D[2][1][0] = 21 ✓
(2, 1, 1) → arr_3D[2][1][1] = 22 ✓
(2, 1, 2) → arr_3D[2][1][2] = 23 ✓
(2, 2, 0) → arr_3D[2][2][0] = 24 ✓
(2, 2, 1) → arr_3D[2][2][1] = 25 ✓
(2, 2, 2) → arr_3D[2][2][2] = 26 ✓

Visual Representation
Let me show you where these values are:

arr_3D = [
  // Depth 0 (no values > 15)
  [
    [0, 1, 2],
    [3, 4, 5],
    [6, 7, 8]
  ],
  // Depth 1 (values 16, 17 at bottom row)
  [
    [9, 10, 11],
    [12, 13, 14],
    [15, 16, 17]   ← 16 at (1,2,1), 17 at (1,2,2)
  ],
  // Depth 2 (ALL values > 15)
  [
    [18, 19, 20],  ← All three values
    [21, 22, 23],  ← All three values
    [24, 25, 26]   ← All three values
  ]
]

In [194]:
arr_3D[np.where(arr_3D > 15)]

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [196]:
arr_3D  # accessing all 2D arrays starting from the second one, all rows starting from the second one, and all columns starting from the second one. The result will be a new array containing the elements [[[13, 14], [16, 17]], [[22, 23], [25, 26]]].

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [195]:
arr_3D[:, 0, :] # Here we are using slicing to access all 2D arrays, the first row of each 2D array, and all columns of the first row. The result will be a new array containing the elements [[0, 1, 2], [9, 10, 11], [18, 19, 20]] since these are the elements in arr_3D that correspond to the specified indices.

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

In [197]:
arr_3D[:, 0]

array([[ 0,  1,  2],
       [ 9, 10, 11],
       [18, 19, 20]])

In [198]:
arr_3D[:, :, 0]

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [ ]:
arr_3D[..., 0]

# Ellipsis ... → means "all dimensions before the last specified one"

# 0 → take ONLY column 0

array([[ 0,  3,  6],
       [ 9, 12, 15],
       [18, 21, 24]])

In [201]:
arr_3D[0, ...]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [202]:
arr_3D[0]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])