NumPy Reshaping & Flattening - Explained with Code

1. Creating the Initial Array: np.arange(12)

In [2]:
import numpy as np
arr = np.arange(12)
print(arr)
print("Shape is", arr.shape)
print("Total size is", arr.size)

# Create a 1D array with numbers 0 to 11
a = np.arange(12)
print("Original 1D array:")
print(a)
print("Shape:", a.shape)  # (12,)
print("Size:", a.size)    # 12 elements

[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape is (12,)
Total size is 12
Original 1D array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)
Size: 12


In [8]:
import numpy as np

# Original 1D array
a = np.arange(12)
print("Original array:")
print(a)
print("Shape:", a.shape)
print()

# Reshape to 3 rows, 4 columns
reshaped = a.reshape(3, 4)
print("Reshaped to 3x4 (3 rows, 4 columns):")
print(reshaped)
print("New shape:", reshaped.shape)
print()

# Reshape to different dimensions
reshaped_2x6 = a.reshape(2, 6)
print("Reshaped to 2x6 (2 rows, 6 columns):")
print(reshaped_2x6)
print("New shape:", reshaped_2x6.shape)

Original array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped to 3x4 (3 rows, 4 columns):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New shape: (3, 4)

Reshaped to 2x6 (2 rows, 6 columns):
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
New shape: (2, 6)


3. Flattening: a.flatten()

In [ ]:
import numpy as np

# Create a 2D array
a = np.arange(12).reshape(3, 4)
print("Original 2D array:")
print(a)
print("Shape:", a.shape)    # (3, 4) 
print()

# Flatten to 1D (returns a COPY)
flattened = a.flatten()
print("Flattened array:")
print(flattened)
print("Shape:", flattened.shape)  # (12,)
print()

# Modify the flattened array
flattened[0] = 999
print("Modified flattened array:")
print("flattened array:", flattened)
print("Original 2D array:")
print(a)
print("→ flatten() creates a COPY, original is safe!")

Original 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)

Flattened array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Modified flattened array:
flattened array: [999   1   2   3   4   5   6   7   8   9  10  11]
Original 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
→ flatten() creates a COPY, original is safe!


4. Ravel: a.ravel()

In [10]:
import numpy as np


# Create a 2D array
a = np.arange(12).reshape(3, 4)
print("Original 2D array:")
print(a)
print("Shape:", a.shape)
print()

# Ravel to 1D (returns a VIEW when possible)
raveled = a.ravel()
print("Raveled array:")
print(raveled)
print("Shape:", raveled.shape)  # (12,)
print()

# Modify the raveled array
raveled[0] = 999
print("Modified raveled array:")
print("Raveled array:", raveled)
print("Original 2D array:")
print(a)
print("→ ravel() returns a VIEW when possible, so original is affected!")

Original 2D array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Shape: (3, 4)

Raveled array:
[ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Modified raveled array:
Raveled array: [999   1   2   3   4   5   6   7   8   9  10  11]
Original 2D array:
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
→ ravel() returns a VIEW when possible, so original is affected!
