NumPy Array Manipulations - Complete Guide with Code
---------------------------------------------------------------------------------------------------------------------


1. np.append() - Adding Elements to Array
📝 Short Explanation
np.append() adds values to the end of an array. You can append along rows (axis=0), columns (axis=1), or flatten everything (axis=None). It always returns a new array - the original remains unchanged.

In [9]:
import numpy as np
a = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print(a)
print(f"Shape: {a.shape}")
print(f"Size: {a.size}")
print()


[[10 20 30]
 [40 50 60]
 [70 80 90]]
Shape: (3, 3)
Size: 9



In [10]:
print("=" * 70)
print("1. np.append() - ADDING ELEMENTS TO ARRAY")
print("=" * 70)

1. np.append() - ADDING ELEMENTS TO ARRAY


In [11]:
# --- Example 1: Appending a row (axis=0) ---
print("Example 1: Appending a row (axis=0)")
new_row = np.array([[100, 110, 120]])
result_append_row = np.append(a, new_row, axis=0)
print("Original array:")
print(a)
print("New row to append:")
print(new_row)
print("Result after appending the new row:")
print(result_append_row)
print()

Example 1: Appending a row (axis=0)
Original array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
New row to append:
[[100 110 120]]
Result after appending the new row:
[[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]



In [13]:
# --- Example 2: Appending a column (axis=1) ---
print("🔹 Appending a COLUMN (axis=1)")
print("-" * 40)
# Append a new column on the right

new_col = np.array([[7], [8], [9]])
print("Original array:")
print(a)
print("New column to append:")
print(new_col) 
print("Result after appending the new column:")
result_col = np.append(a, new_col, axis=1)
print(result_col)

🔹 Appending a COLUMN (axis=1)
----------------------------------------
Original array:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
New column to append:
[[7]
 [8]
 [9]]
Result after appending the new column:
[[10 20 30  7]
 [40 50 60  8]
 [70 80 90  9]]


In [15]:
# --- Example 4: Appending multiple rows ---
print("🔹 Appending MULTIPLE ROWS")
print("-" * 40)
# Append multiple rows
a2 = np.array([[1, 2, 3],
               [4, 5, 6]])
multiple_rows = np.array([[7, 8, 9],
                          [10, 11, 12]])
result_multiple = np.append(a2, multiple_rows, axis=0)
print(result_multiple)

🔹 Appending MULTIPLE ROWS
----------------------------------------
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


2. np.delete() - Removing Elements

📝 Short Explanation

np.delete() removes rows or columns from an array by index. You specify the axis (0 for rows, 1 for columns) and the index(es) to remove. Like append, it returns a new array - original is untouched.

In [16]:
print("=" * 70)
print("2. np.delete() - REMOVING ELEMENTS FROM ARRAY")
print("=" * 70)

2. np.delete() - REMOVING ELEMENTS FROM ARRAY


In [18]:
print("\n Original array a2: ")
print(a2)
print(f"shape: {a2.shape}")
print(f"size: {a2.size}")
print()



 Original array a2: 
[[1 2 3]
 [4 5 6]]
shape: (2, 3)
size: 6



In [19]:
# Remove row at index 1 (second row)
reult_delete_row = np.delete(a2, 1, axis=0)
print("After deleting row at index 1:")
print(reult_delete_row)


After deleting row at index 1:
[[1 2 3]]


In [28]:
print("\n Original array result_multiple: ")
print(result_multiple)
print(f"shape: {result_multiple.shape}")
print(f"size: {result_multiple.size}")
print()

print(f"(removing row at index 0 and column at index 1)")
result_delete_row_col = np.delete(result_multiple, [0, 1], axis=0)  # Remove row at index 0 and column at index 1   
print("After deleting row at index 0 and column at index 1:")
print(result_delete_row_col)


 Original array result_multiple: 
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
shape: (4, 3)
size: 12

(removing row at index 0 and column at index 1)
After deleting row at index 0 and column at index 1:
[[ 7  8  9]
 [10 11 12]]


In [29]:
# --- Example 4: Remove by negative index ---
print("🔹 Removing by NEGATIVE INDEX")
result_negative = np.delete(a, -1, axis=0)  # Remove last row

print(f"Original:\n{a}")
print(f"Removing last row (index -1)")
print(f"Result:\n{result_negative}")
print()
result_negative = np.delete(a, -1, axis=1)  # Remove last column
print(f"Removing last column (index -1)")
print(f"Result:\n{result_negative}")
print()


🔹 Removing by NEGATIVE INDEX
Original:
[[10 20 30]
 [40 50 60]
 [70 80 90]]
Removing last row (index -1)
Result:
[[10 20 30]
 [40 50 60]]

Removing last column (index -1)
Result:
[[10 20]
 [40 50]
 [70 80]]



3. .T and np.transpose() - Transposing Arrays

📝 Short Explanation

Transpose swaps rows and columns in a 2D array (flips the matrix). For 2D arrays, .T and np.transpose() do the same thing. For 3D+ arrays, you can specify which axes to swap.

In [30]:
import numpy as np

print("=" * 70)
print("3. .T and np.transpose() - TRANSPOSING ARRAYS")
print("=" * 70)


# --- Example 1: 2D Array Transpose ---
print("🔹 2D Array Transpose (swaps rows ↔ columns)")
print("-" * 40)


a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(f"Original array (2x3):")
print(a)
print(f"Shape: {a.shape}")
print()

3. .T and np.transpose() - TRANSPOSING ARRAYS
🔹 2D Array Transpose (swaps rows ↔ columns)
----------------------------------------
Original array (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)



In [31]:
# Using .T
transpose_t = a.T
print("Transposed array using .T:")
print(transpose_t)
print(f"Shape: {transpose_t.shape}") #(3 rows, 2 columns)
print()

Transposed array using .T:
[[1 4]
 [2 5]
 [3 6]]
Shape: (3, 2)



In [35]:
a2 = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
transpose_func = np.transpose(a2)
print(f"Transposed array using np.transpose():")
print(transpose_func)
print(f"Shape: {transpose_func.shape}") #(3 rows, 2 columns)
print()
# --- Example 2: 3D Array Transpose ---
print("🔹 3D Array Transpose")
print("-" * 40)

Transposed array using np.transpose():
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Shape: (3, 3)

🔹 3D Array Transpose
----------------------------------------


In [36]:
# Create a 3D array with shape (2, 3, 4)
c= np.arange(24).reshape((2, 3, 4))
print(f"Original 3D array (shape {c.shape}):")
print("Dimensions: (2, 3, 4) -> 2 blocks, each with 3 rows and 4 columns")
print(c)
print()

Original 3D array (shape (2, 3, 4)):
Dimensions: (2, 3, 4) -> 2 blocks, each with 3 rows and 4 columns
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]



In [37]:
# Transpose with axes argument
# Original order: (0, 1, 2) → New order: (1, 0, 2)

transposed_c = np.transpose(c, axes=(1, 0, 2))
print(f"Transposed 3D array (shape {transposed_c.shape}):")
print("Dimensions: (3, 2, 4) -> 3 blocks, each with 2 rows and 4 columns")
print(transposed_c)
print()

Transposed 3D array (shape (3, 2, 4)):
Dimensions: (3, 2, 4) -> 3 blocks, each with 2 rows and 4 columns
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]



In [38]:
# Another permutation
transposed_3d_v2 = np.transpose(c, (2, 0, 1))
print(f"Transposed 3D array with axes (2, 0, 1) (shape {transposed_3d_v2.shape}):")
print("Dimensions: (4, 2, 3) -> 4 blocks, each with 2 rows and 3 columns")
print(transposed_3d_v2)
print() 

Transposed 3D array with axes (2, 0, 1) (shape (4, 2, 3)):
Dimensions: (4, 2, 3) -> 4 blocks, each with 2 rows and 3 columns
[[[ 0  4  8]
  [12 16 20]]

 [[ 1  5  9]
  [13 17 21]]

 [[ 2  6 10]
  [14 18 22]]

 [[ 3  7 11]
  [15 19 23]]]



In [39]:
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print("Original (3x4):")
print(matrix)
print()
print("Transposed (4x3):")
print(matrix.T)
print()


Original (3x4):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Transposed (4x3):
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]



4. np.concatenate() - Joining Arrays

📝 Short Explanation

np.concatenate() joins arrays along an existing axis. For vertical stacking (axis=0), arrays must have same number of columns. For horizontal stacking (axis=1), arrays must have same number of rows.

In [40]:
import numpy as np

print("=" * 70)
print("4. np.concatenate() - JOINING ARRAYS")
print("=" * 70)

4. np.concatenate() - JOINING ARRAYS


In [41]:
# Create arrays
a = np.array([[1, 2], 
              [3, 4]])
b = np.array([[5, 6]])
c = np.array([[7, 8],
              [9, 10]])
print("Original arrays:")
print(f"Array a (2x2):\n{a}")
print(f"Array b (1x2):\n{b}")
print(f"Array c (2x2):\n{c}")

Original arrays:
Array a (2x2):
[[1 2]
 [3 4]]
Array b (1x2):
[[5 6]]
Array c (2x2):
[[ 7  8]
 [ 9 10]]


In [42]:
# --- Example 1: Vertical concatenation (axis=0) ---
print("🔹 Vertical Concatenation (axis=0)")
print("-" * 40)

🔹 Vertical Concatenation (axis=0)
----------------------------------------


In [46]:
result_vertical = np.concatenate((a, b, c), axis=0)
print(f"Result of vertical concatenation: {result_vertical.shape} ")
print(result_vertical)
# --- Example 2: Horizontal concatenation (axis=1) ---

Result of vertical concatenation: (5, 2) 
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [54]:
# --- Example 2: Horizontal concatenation (axis=1) ---
print("🔹 Horizontal Concatenation (axis=1)")
print("-" * 40)


result_horizontal = np.concatenate((a, a), axis=1)
print(f"Result of horizontal concatenation: {result_horizontal.shape}") 
print(result_horizontal)

result_horizontalv2 = np.concatenate((c, a), axis=1)
print(f"Result of horizontal concatenation: {result_horizontalv2.shape}") 
print(result_horizontalv2)

🔹 Horizontal Concatenation (axis=1)
----------------------------------------
Result of horizontal concatenation: (2, 4)
[[1 2 1 2]
 [3 4 3 4]]
Result of horizontal concatenation: (2, 4)
[[ 7  8  1  2]
 [ 9 10  3  4]]


In [55]:
# --- Example 5: Concatenating multiple arrays ---
print("🔹 Concatenating Multiple Arrays")

print("-" * 40)
d = np.array([[11, 12]])
result_multiple = np.concatenate((a, c, d), axis=0)
print(f"Concatenating a, c, and d vertically:")
print(result_multiple)
print(f"Shape: {result_multiple.shape}")
print()


🔹 Concatenating Multiple Arrays
----------------------------------------
Concatenating a, c, and d vertically:
[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]
 [11 12]]
Shape: (5, 2)



5. Axis Swapping with .swapaxes() and .T

📝 Short Explanation

swapaxes() exchanges two dimensions of an array. For 2D arrays, swapaxes(0,1) is equivalent to transpose. For higher dimensions, it's more flexible.

In [56]:
import numpy as np

print("=" * 70)
print("5. Axis Swapping - .swapaxes() and .T")
print("=" * 70)

# --- Example 1: 2D Array Swap (equivalent to transpose) ---
print("🔹 2D Array - Swapping Axes")
print("-" * 40)

a = np.array([[1, 2, 3],
              [4, 5, 6]])
print(f"Original array (2x3):")
print(a)
print(f"Shape: {a.shape}")
print()


5. Axis Swapping - .swapaxes() and .T
🔹 2D Array - Swapping Axes
----------------------------------------
Original array (2x3):
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)



In [57]:
# Using .T
print("Using a.T:")
print(a.T)
print()

Using a.T:
[[1 4]
 [2 5]
 [3 6]]



In [58]:
# Using swapaxes
print("Using a.swapaxes(0, 1):")
print(a.swapaxes(0, 1))
print("(Same result as .T for 2D arrays)")
print()

Using a.swapaxes(0, 1):
[[1 4]
 [2 5]
 [3 6]]
(Same result as .T for 2D arrays)



In [60]:
# --- Example 2: 3D Array Swap ---
print("🔹 3D Array - Swapping Specific Axes")
print("-" * 40)

# Create 3D array with shape (2, 3, 4)
b = np.arange(24).reshape(2, 3, 4)
print(f"Original 3D array shape: {b.shape}")
print(b)
print("Dimensions: (depth, rows, columns)")
print()

🔹 3D Array - Swapping Specific Axes
----------------------------------------
Original 3D array shape: (2, 3, 4)
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
Dimensions: (depth, rows, columns)



In [62]:
# Swap axis 0 and axis 1
swapped_01 = b.swapaxes(0, 1)
print(f"After b.swapaxes(0, 1):")
print(f"New shape: {swapped_01.shape}")
print("(rows, depth, columns)")
print(swapped_01)
print()

After b.swapaxes(0, 1):
New shape: (3, 2, 4)
(rows, depth, columns)
[[[ 0  1  2  3]
  [12 13 14 15]]

 [[ 4  5  6  7]
  [16 17 18 19]]

 [[ 8  9 10 11]
  [20 21 22 23]]]



In [63]:
swapped_12 = b.swapaxes(1, 2)
print(f"After b.swapaxes(1, 2):")
print(f"New shape: {swapped_12.shape}")
print("(depth, columns, rows)")
print()
print(swapped_12)

After b.swapaxes(1, 2):
New shape: (2, 4, 3)
(depth, columns, rows)

[[[ 0  4  8]
  [ 1  5  9]
  [ 2  6 10]
  [ 3  7 11]]

 [[12 16 20]
  [13 17 21]
  [14 18 22]
  [15 19 23]]]
