In [1]:
import numpy as np

In [2]:
lst_arr1 = [1, 2, 3]
arr1 = np.array(lst_arr1)
lst_arr2 = [4, 5, 6]
arr2 = np.array(lst_arr2)
print(arr1)
print(arr2)

[1 2 3]
[4 5 6]


In [3]:
dot_product = 0
for i in range(len(lst_arr1)): dot_product += lst_arr1[i] * lst_arr2[i]

dot_product
#here we are calculating the dot product of two arrays using a for loop. The dot product is calculated by multiplying corresponding elements of the two arrays and summing the results. In this case, the dot product of arr1 and arr2 is 32 (1*4 + 2*5 + 3*6 = 4 + 10 + 18 = 32).

32

In [5]:
dot_product = np.dot(arr1, arr2)
dot_product

np.int64(32)

In [6]:
lst_large_arr1 = list(range(1, 100000))
lst_large_arr2 = list(range(1, 100000))

large_arr1 = np.array(lst_large_arr1)
large_arr2 = np.array(lst_large_arr2)

In [7]:
import time
start_time = time.time()
dot_product = 0
for i in range(len(lst_large_arr1)):
    dot_product += lst_large_arr1[i] * lst_large_arr2[i]
print('Time taken to calculate the dot product for two large arrays using a loop:', time.time() - start_time)
print()

start_time = time.time()
np.dot(large_arr1, large_arr2)
print('Time taken to calculate the dot product for two large arrays using NumPy:', time.time() - start_time)

Time taken to calculate the dot product for two large arrays using a loop: 0.009071588516235352

Time taken to calculate the dot product for two large arrays using NumPy: 0.0002503395080566406


In [15]:
lst_mat1 = [[1, 2], [3, 4], [5, 6]]
mat1 = np.array(lst_mat1)
lst_mat2 = [[7, 8], [9, 10], [11, 12]]
mat2 = np.array(lst_mat2)
print('Matrix 1:\n', mat1)  
print('Matrix 2:\n', mat2)  
mat1.shape, mat2.shape

Matrix 1:
 [[1 2]
 [3 4]
 [5 6]]
Matrix 2:
 [[ 7  8]
 [ 9 10]
 [11 12]]


((3, 2), (3, 2))

In [22]:
# Make mat2 have shape (2, 3) instead of (3, 2)
result = np.dot(mat1, mat2.T)  # .T transposes the matrix
print("Matrix multiplication:") 
print(result)
# here calculation formula for each element in the resulting matrix is as follows:
# result [[ 23  29  35], [ 53  67  81], [ 83 105 127]]
# its formula is as follows:
# result[0, 0] = mat1[0, 0] * mat2[0, 0] + mat1[0, 1] * mat2[1, 0] = 1*7 + 2*9 = 23
# result[0, 1] = mat1[0, 0] * mat2[0, 1] + mat1[0, 1] * mat2[1, 1] = 1*8 + 2*10 = 29
# result[0, 2] = mat1[0, 0] * mat2[0, 2] + mat1[0, 1] * mat2[1, 2] = 1*9 + 2*11 = 35
# result[1, 0] = mat1[1, 0] * mat2[0, 0] + mat1[1, 1] * mat2[1, 0] = 3*7 + 4*9 = 53
# result[1, 1] = mat1[1, 0] * mat2[0, 1] + mat1[1, 1] * mat2[1, 1] = 3*8 + 4*10 = 67
# result[1, 2] = mat1[1, 0] * mat2[0, 2] + mat1[1, 1] * mat2[1, 2] = 3*9 + 4*11 = 81
# result[2, 0] = mat1[2, 0] * mat2[0, 0] + mat1[2, 1] * mat2[1, 0] = 5*7 + 6*9 = 83
# result[2, 1] = mat1[2, 0] * mat2[0, 1] + mat1[2, 1] * mat2[1, 1] = 5*8 + 6*10 = 94

Matrix multiplication:
[[ 23  29  35]
 [ 53  67  81]
 [ 83 105 127]]


In [21]:
# If you want element-wise multiplication (same shape)
result = mat1 * mat2  # NOT np.dot()

print("Element-wise multiplication:")
print(result)
print("Shape:", result.shape)  # (3, 2)

Element-wise multiplication:
[[ 7 16]
 [27 40]
 [55 72]]
Shape: (3, 2)


In [25]:
#The @ operator is specifically designed for matrix multiplication. It's the same as np.matmul() and similar to np.dot() for 2D arrays.
result2= mat1 @ mat2.T
result2

array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])

mat1 @ mat2 (when shapes are compatible):

Example: mat1 (2×3) @ mat2 (3×2)
┌─────────────────────────────────────────────────────┐
│                                                     │
│  mat1 = [[1, 2, 3],      mat2 = [[7, 8],          │
│          [4, 5, 6]]               [9, 10],         │
│                                   [11, 12]]        │
│                                                     │
│  Step-by-step multiplication:                      │
│                                                     │
│  Result[0,0] = [1,2,3] · [7,9,11] = 1×7+2×9+3×11 │
│              = 7 + 18 + 33 = 58                    │
│                                                     │
│  Result[0,1] = [1,2,3] · [8,10,12] = 1×8+2×10+3×12│
│              = 8 + 20 + 36 = 64                    │
│                                                     │
│  Result[1,0] = [4,5,6] · [7,9,11] = 4×7+5×9+6×11 │
│              = 28 + 45 + 66 = 139                  │
│                                                     │
│  Result[1,1] = [4,5,6] · [8,10,12] = 4×8+5×10+6×12│
│              = 32 + 50 + 72 = 154                  │
│                                                     │
│  Final Result: [[58, 64],                          │
│                 [139, 154]]                        │
└─────────────────────────────────────────────────────┘

In [30]:
np.matmul(mat1, mat2.T)

array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]])

In [31]:
arr1

array([1, 2, 3])

In [32]:
mat1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
arr1.sum()

np.int64(6)

In [28]:
mat1.sum()

np.int64(21)

In [33]:
mat1.sum(axis=0)  # Sum along columns

array([ 9, 12])

In [34]:
mat1.sum(axis=1)  # Sum along rows

array([ 3,  7, 11])

In [35]:
mat1.max()

np.int64(6)

In [37]:
mat1.max(axis=1)  # Sum along rows

array([2, 4, 6])

In [38]:
arr1.mean()

np.float64(2.0)

In [39]:
mat1.mean()

np.float64(3.5)

In [40]:
mat1.mean(axis=1)

array([1.5, 3.5, 5.5])

In [43]:
arr1

array([1, 2, 3])

In [44]:
arr2

array([4, 5, 6])

In [46]:
arr3 = np.array([[7, 8, 9, -5]])
arr3

array([[ 7,  8,  9, -5]])

In [49]:
np.abs(arr3)  # Absolute value of each element in arr3 like -5 becomes 5, 7 stays 7, etc.


array([[7, 8, 9, 5]])

In [50]:
np.sqrt(arr3)  # Square root of each element in arr3 like 4 becomes 2, 9 becomes 3, etc and for negative numbers it will return nan (not a number) because square root of negative numbers is not defined in the real number system.

/tmp/ipykernel_501867/105866615.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(arr3)  # Square root of each element in arr3 like 4 becomes 2, 9 becomes 3, etc and for negative numbers it will return nan (not a number) because square root of negative numbers is not defined in the real number system.


array([[2.64575131, 2.82842712, 3.        ,        nan]])

In [51]:
np.log(arr3)  # Natural logarithm of each element in arr3 like e becomes 1, e^2 becomes 2, etc and for negative numbers it will return nan (not a number) because logarithm of negative numbers is not defined in the real number system.


/tmp/ipykernel_501867/986500166.py:1: RuntimeWarning: invalid value encountered in log
  np.log(arr3)  # Natural logarithm of each element in arr3 like e becomes 1, e^2 becomes 2, etc and for negative numbers it will return nan (not a number) because logarithm of negative numbers is not defined in the real number system.


array([[1.94591015, 2.07944154, 2.19722458,        nan]])

In [52]:
np.power(arr2, 0.5)

array([2.        , 2.23606798, 2.44948974])

In [53]:
np.sort(arr3)

array([[-5,  7,  8,  9]])

In [56]:
#np.sort(arr3, ascending = False)
np.sort(arr3)[::-1]

array([[-5,  7,  8,  9]])

In [58]:
arr3.argsort()
#here it returns the index of the sorted array in order

array([[3, 0, 1, 2]])