In [53]:
import numpy as np

In [54]:
arr = np.array(['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy'])
arr

array(['Ashok', 'Ravi', 'Kumar', 'Shiela', 'P.', 'Reddy'], dtype='<U6')

In [55]:
   arr.size 

6

In [56]:
np.reshape(arr, (2, 3))

array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

In [57]:
arr.reshape(2, 3)

array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

In [58]:
np.reshape(arr, (1, 3, 2))

array([[['Ashok', 'Ravi'],
        ['Kumar', 'Shiela'],
        ['P.', 'Reddy']]], dtype='<U6')

In [59]:
np.reshape(arr, (2, 3))
np.reshape(arr, (6, 1, 1)) 

array([[['Ashok']],

       [['Ravi']],

       [['Kumar']],

       [['Shiela']],

       [['P.']],

       [['Reddy']]], dtype='<U6')

In [60]:
np.reshape(arr, (-1, 3)) # Here, -1 means "unspecified.reshape(arr, (-1, 3)) # Here, -1 means "unspecified", so NumPy will automatically calculate the appropriate size for that dimension based on the size of the original array and the other specified dimensions. In this case, it will create a new array with 2 rows and 3 columns, since the original array has 6 elements.


array([['Ashok', 'Ravi', 'Kumar'],
       ['Shiela', 'P.', 'Reddy']], dtype='<U6')

In [61]:
mat = np.array([['Apple', 'Bread', 'Cheese'], ['Rs. 120', 'Rs. 20', 'Rs. 150']])
mat

array([['Apple', 'Bread', 'Cheese'],
       ['Rs. 120', 'Rs. 20', 'Rs. 150']], dtype='<U7')

In [62]:
mat.shape

(2, 3)

In [63]:
mat.T

array([['Apple', 'Rs. 120'],
       ['Bread', 'Rs. 20'],
       ['Cheese', 'Rs. 150']], dtype='<U7')

In [64]:
np.transpose(mat)

array([['Apple', 'Rs. 120'],
       ['Bread', 'Rs. 20'],
       ['Cheese', 'Rs. 150']], dtype='<U7')

In [65]:
transposed_mat = mat.transpose()
transposed_mat.shape

(3, 2)

In [66]:
three_tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
three_tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [67]:
three_tensor.T

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [68]:
three_tensor.shape

(2, 2, 2)

In [69]:
three_tensor

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [70]:
three_tensor.transpose(2, 1, 0)

array([[[1, 5],
        [3, 7]],

       [[2, 6],
        [4, 8]]])

In [71]:
three_tensor.transpose((1, 0, 2))

array([[[1, 2],
        [5, 6]],

       [[3, 4],
        [7, 8]]])

In [72]:
mat

array([['Apple', 'Bread', 'Cheese'],
       ['Rs. 120', 'Rs. 20', 'Rs. 150']], dtype='<U7')

In [73]:
mat.ravel() #here, ravel() returns a flattened 1D array containing all the elements of the original array. It does not create a new copy of the data; instead, it returns a view of the original array whenever possible. If the original array is not contiguous in memory, ravel() may return a copy instead. 

array(['Apple', 'Bread', 'Cheese', 'Rs. 120', 'Rs. 20', 'Rs. 150'],
      dtype='<U7')

In [74]:
mat.flatten() #here, flatten() returns a flattened 1D array as well, but it always creates a new copy of the data, regardless of whether the original array is contiguous in memory or not. This means that any changes made to the flattened array will not affect the original array.

array(['Apple', 'Bread', 'Cheese', 'Rs. 120', 'Rs. 20', 'Rs. 150'],
      dtype='<U7')

In [75]:
three_tensor.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
arr = np.arange(36)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [81]:
arr.shape

(36,)

In [86]:
reshaped_4x6 = arr.reshape(4, 9)
reshaped_4x6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [83]:
reshaped_arr[1, 3]

np.int64(9)

In [ ]:
reshaped_2x3x4 = arr.reshape(2, 3, 6)
reshaped_2x3x4

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]]])

In [ ]:
reshaped_2x3x4[1, 2, 4]

np.int64(34)

In [ ]:
## 4D array not possible
# reshaped_2x2x2x3 = arr.reshape(2, 2, 2, 3)
#reshaped_2x2x2x3

In [90]:
arr1 = np.arange(24)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [95]:
reshaped_2x2x2x3 = arr1.reshape(2, 2, 2, 3)
reshaped_2x2x2x3

array([[[[ 0,  1,  2],
         [ 3,  4,  5]],

        [[ 6,  7,  8],
         [ 9, 10, 11]]],


       [[[12, 13, 14],
         [15, 16, 17]],

        [[18, 19, 20],
         [21, 22, 23]]]])

In [96]:
reshaped_2x2x2x3[0, 1, 0, 2]

np.int64(8)

In [97]:
reshaped_2x2x2x3[..., 2]

array([[[ 2,  5],
        [ 8, 11]],

       [[14, 17],
        [20, 23]]])

In [99]:
reshaped_2x2x2x3[1, ...]

array([[[12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23]]])

In [101]:
from hmac import new


new_data = np.arange(24, 36)
new_data

array([24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [102]:
new_data.shape

(12,)

In [107]:
new_data_1x6 = new_data.reshape(2, 6)
new_data_1x6

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [108]:
new_data_1x6 = new_data.reshape(-1, 6)
new_data_1x6

array([[24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [110]:
new_data_6x1 = new_data.reshape(6, -1)
new_data_6x1

array([[24, 25],
       [26, 27],
       [28, 29],
       [30, 31],
       [32, 33],
       [34, 35]])