In [17]:
import numpy as np

In [18]:
data = np.random.uniform(low = 10, high = 40, size = (365, 5))  # creating random data for the purposes of our problem

In [19]:
# weekly_data = data.reshape(-1, 7, 5)  # why won't this work?

In [20]:
rows_needed = 7 - (data.shape[0] % 7)
rows_needed

6

In [25]:
new_length = data.shape[0] + rows_needed 
new_length

371

In [27]:
padded_data = np.zeros((new_length, data.shape[1]))
padded_data

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], shape=(371, 5))

In [28]:
padded_data[:data.shape[0], :] = data 
padded_data #here we have padded the data with zeros to make it divisible by 7  

array([[10.76545189, 36.69255346, 39.91335013, 17.21219191, 10.56568919],
       [37.3957859 , 23.04665331, 13.31815822, 28.77468273, 32.97285082],
       [13.10643689, 25.31053312, 38.04586179, 36.57321385, 12.46625557],
       ...,
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
      shape=(371, 5))

In [21]:
rows_needed = 7 - (data.shape[0] % 7)  # calculating how many rows are needed to fill up the last week
new_length = data.shape[0] + rows_needed  # new length after adding the padding

padded_data = np.zeros((new_length, data.shape[1]))  # making an empty 2D array to store our data

padded_data[:data.shape[0], :] = data  # copying the original data into the empty array
padded_data

array([[10.76545189, 36.69255346, 39.91335013, 17.21219191, 10.56568919],
       [37.3957859 , 23.04665331, 13.31815822, 28.77468273, 32.97285082],
       [13.10643689, 25.31053312, 38.04586179, 36.57321385, 12.46625557],
       ...,
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
      shape=(371, 5))

In [22]:
weekly_data = padded_data.reshape(-1, 7, 5)
weekly_data.shape  # one extra row's worth of padding will be reflected in the dimensions

(53, 7, 5)

In [31]:
padded_data_2 = np.concatenate((data, np.zeros((rows_needed, 5))), axis = 0)
padded_data_2 
#here we have padded the data with zeros to make it divisible by 7, using a different method

array([[10.76545189, 36.69255346, 39.91335013, 17.21219191, 10.56568919],
       [37.3957859 , 23.04665331, 13.31815822, 28.77468273, 32.97285082],
       [13.10643689, 25.31053312, 38.04586179, 36.57321385, 12.46625557],
       ...,
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
      shape=(371, 5))

In [30]:
padded_data == padded_data_2 # we can see that both the arrays are equal

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       ...,
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]], shape=(371, 5))

In [32]:
np.array_equal(padded_data, padded_data_2) #here we can see that both the arrays are equal, using a different method    

True

In [34]:
weekly_data_2 = padded_data_2.reshape(-1, 7, 5)
weekly_data_2

array([[[10.76545189, 36.69255346, 39.91335013, 17.21219191,
         10.56568919],
        [37.3957859 , 23.04665331, 13.31815822, 28.77468273,
         32.97285082],
        [13.10643689, 25.31053312, 38.04586179, 36.57321385,
         12.46625557],
        ...,
        [25.04210333, 32.38603671, 38.94187129, 39.44078338,
         31.56208012],
        [33.66365702, 10.59836307, 37.63156036, 11.06053705,
         31.11162818],
        [34.64500489, 26.33445484, 11.33169652, 39.21763152,
         15.87362213]],

       [[15.33720614, 18.78037449, 11.50338929, 13.97295864,
         37.39822183],
        [22.50996502, 28.06331681, 12.76595932, 21.47179972,
         11.20135327],
        [19.00340204, 19.30061855, 34.04857332, 34.29091699,
         35.49876928],
        ...,
        [16.59257471, 15.65758269, 19.88297999, 31.42478429,
         30.90991377],
        [13.3171684 , 28.53673627, 24.70326982, 28.02597312,
         26.00058493],
        [32.82944033, 11.33923025, 27.95734298, 

In [35]:
weekly_data = padded_data.reshape(-1, 7, 5)
weekly_data.shape
# we can see that both the arrays are equal

(53, 7, 5)

In [36]:
weekly_data[13, 1, 4]

np.float64(18.70834479711924)

In [37]:
weekly_data[-1]

array([[17.14514665, 25.74894489, 19.15110783, 19.93777075, 34.41260012],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])